name: Go Tests
on: [push, pull_request]

jobs:
  verify-gomod:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          stable: true

      - name: Check code
        uses: actions/checkout@v2

      - run: go mod tidy

      - name: Verify no changes from go mod tidy.
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git status    # These are the files that failed to pass the check.
            exit 1
          fi
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
          stable: true

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: |
          make test
